### ISSUE TITLE
error during execution of train_graphvit.py: Mask shape does not match input

### ISSUE THREAD

**Issue by s-kuenzli** [eagle-dataset/EagleMeshTransformer#2]
Hello 

We tried to run your model, when executing train_graphvit.py with the default arguments (only specifing dataset_path) the following error occurs:
Traceback (most recent call last):
  File "/itet-stor/skuenzli/home/EagleTest/EagleMeshTransformer/train_graphvit.py", line 257, in <module>
    main()
  File "/itet-stor/skuenzli/home/EagleTest/EagleMeshTransformer/train_graphvit.py", line 244, in main
    error = validate(model, valid_dataloader, epoch=epoch)
  File "/itet-stor/skuenzli/home/EagleTest/EagleMeshTransformer/train_graphvit.py", line 176, in validate
    state_hat, output, target = model(mesh_pos, edges, state, node_type, clusters, clusters_mask,
  File "/itet-stor/skuenzli/net_scratch/conda_envs/eagle/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/srv/homes01/itet_isg_homes_02/skuenzli/EagleTest/EagleMeshTransformer/Models/GraphViT.py", line 50, in forward
    W = a(W, attention_mask, cluster_posenc)
  File "/itet-stor/skuenzli/net_scratch/conda_envs/eagle/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/srv/homes01/itet_isg_homes_02/skuenzli/EagleTest/EagleMeshTransformer/Models/GraphViT.py", line 88, in forward
    W2 = self.attention(W1_posenc, W1_posenc, W1_posenc, attn_mask=attention_mask)[0]
  File "/itet-stor/skuenzli/net_scratch/conda_envs/eagle/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/itet-stor/skuenzli/net_scratch/conda_envs/eagle/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1144, in forward
    return torch._native_multi_head_attention(
RuntimeError: Mask shape should match input. mask: [4, 181, 181] input: [1, 4, 181, 181]

Potential Solution:
replacing line 88 in GraphViT.py with:
        W2 = self.attention(W1_posenc, W1_posenc, W1_posenc, attn_mask=attention_mask[0])[0]
instead of:
        W2 = self.attention(W1_posenc, W1_posenc, W1_posenc, attn_mask=attention_mask)[0]
seems to work, could you confirm?
Thanks!

**Comment by SteevenJanny** [comment]
Hello ! 
Thank you for your feedback ! I think the error might come from a PyTorch version : the function raising the error ```torch._native_multi_head_attention```isn't used in Pytorch 1.13 when a mask is provided or in training mode. In Pytorch 2.0, the function can be used during eval even with a mask, but seems to generate errors : https://github.com/pytorch/pytorch/issues/97409

I could not reproduce the same error as you (probably because you are using an intermediate version of PyTorch), so the easiest fix I see would be to downgrade PyTorch to 1.13. If you could give me your version of PyTorch, I will be happy to confirm !

I cannot guarantee that your solution actually work, as I am not sure how ```torch._native_multi_head_attention``` actually behave. Based on the issue above, I think you could solve the problem by adding : ```model.attention.train()``` in the ```validate``` function to prevent using the fast_path mode of MHA, It should not change the behavior of the model since dropout isn't used in the MHA.

**Comment by s-kuenzli** [comment]
Hello!

Thank you very much for you quick and elaborate answer! 
Running with PyTorch 1.13 everything works perfectly.
I used PyTorch 2.0.0, but as it works with PyTorch 1.13 this is fine for me.
Thanks again.
